int main(){
    
    file target;
    string handle;

    handle="apple"; 
    target=open("originalFile.txt", "r");
    print_s(target);
    find&replace(handle, bananas, target, );

    return 0;
}


string findreplace(string handle, string newword, file original, file destination){

    while(i<l){
        temp[0]=target[i];
        tempup[0]=toupper(temp[0]);
        ans[i]=tempup[0];
        i=i+1;            
    }

    return ans;
}
